name: flutter_design_patterns
description: App which can help to learning design patterns and implement them with Flutter.
version: 1.0.4+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  effective_dart: ^1.3.2
  yaml: ^3.1.1
  provider: ^6.0.4
  flutter_markdown: ^0.6.13
  xml: ^6.0.1
  faker: ^2.0.0
  font_awesome_flutter: ^10.2.1
  sqflite: ^2.2.0+3
  path_provider: ^2.0.11
  path: ^1.8.2
  flutter_native_splash: ^2.2.14
  shared_preferences: ^2.0.15
  day_night_switcher: ^0.2.0+1
  auto_route: ^5.0.2

dev_dependencies:
  auto_route_generator: ^5.0.3
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dart_code_metrics: ^5.0.1
  build_runner: ^2.3.2

flutter_native_splash:
  image: "assets/images/app_icon.png"
  color: "8E93B3"
  android_disable_fullscreen: true

  dart_code_metrics: ^5.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/config/config_design_patterns.json
    - assets/markdown/
